import {
  drawerWidth,
  transition,
  whiteColor,
  blackColor,
  defaultFont,
  blackColorTheme,
  whiteColorTheme
} from "./commonStyles";

export const drawerStyles = (theme) => ({
  root: {
    display: "flex",
  },
  drawer: {
    width: drawerWidth,
    flexShrink: 0,
  },
  drawerPaper: {
    border: "none",
    position: "fixed",
    // boxShadow:"0px 2px 4px -1px rgb(0 0 0 / 20%)  0px 4px 5px 0px rgb(0 0 0 / 14%)  0px 1px 10px 0px rgb(0 0 0 / 12%)",
    top: "0",
    bottom: "0",
    left: "0",
    zIndex: "1032",
    transitionProperty: "top, bottom, width",
    transitionDuration: ".2s, .2s, .35s",
    transitionTimingFunction: "linear, linear, ease",
    // borderRight:"1px solid",
    // overflow: 'auto',
    width: drawerWidth,
    [theme.breakpoints.up("md")]: {
      width: drawerWidth,
      position: "fixed",
      height: "100%",
    },
    [theme.breakpoints.down("sm")]: {
      width: drawerWidth,
      position: "fixed",
      // display: "block",
      top: "0",
      bottom:"0",
      height: "100%",
      right: "0",
      left: "auto",
      zIndex: "1032",
      // visibility: "visible",
      // overflowY: "visible",
      // borderTop: "none",
      textAlign: "left",
      // paddingRight: "0px",
      // paddingLeft: "0",
      // transform: `translate3d(${drawerWidth}px, 0, 0)`,
      // ...transition,
    },
    "&:before,&:after": {
      position: "absolute",
      zIndex: "3",
      width: "100%",
      height: "100%",
      content: '""',
      display: "block",
      top: "0",
    },
  },
  drawerHeader: {
    display: "flex",
    alignItems: "center",
    padding: theme.spacing(0, 1),
    // necessary for content to be below app bar
    ...theme.mixins.toolbar,
  },
  logo: {
    padding: "15px 0px",
    margin: "0",
    display: "block",
    position: "relative",
    zIndex: "4",
    "&:after": {
      content: '""',
      position: "absolute",
      bottom: "0",
      height: "0px",
      right: "15px",
      width: "calc(100% - 30px)",
      borderBottom: "1px solid",
    },
  },
  logoMini: {
    transition: "all 300ms linear",
    opacity: 1,
    float: "left",
    textAlign: "center",
    width: "30px",
    display: "inline-block",
    maxHeight: "30px",
    marginLeft: "22px",
    marginRight: "18px",
    marginTop: "7px",
    color: "inherit"
  },
  logoNormal: {
    ...defaultFont,
    transition: "all 300ms linear",
    display: "block",
    opacity: "1",
    transform: "translate3d(0px, 0, 0)",
    textTransform: "uppercase",
    padding: "5px 0px",
    fontSize: "18px",
    whiteSpace: "nowrap",
    fontWeight: "400",
    lineHeight: "30px",
    overflow: "hidden",
    "&,&:hover,&:focus": {
      color: "inherit"
    }
  },
  logoImage: {
    width: "35px",
    border: 0,
    verticalAlign: "middle",
  },
  ...blackColorTheme,
  ...whiteColorTheme,
  list: {
    marginTop: "15px",
    paddingLeft: "0",
    paddingTop: "0",
    paddingBottom: "0",
    marginBottom: "0",
    listStyle: "none",
    color: "inherit",
    "&:before,&:after": {
      display: "table",
      content: '" "',
    },
    "&:after": {
      clear: "both",
    },
  },
  draggingList:{
    color:`${blackColor} !important`,
    width: "auto",
    margin: "2px 10px 0",
    padding: "2px 15px",
    position: "relative",
    fontWeight: 300,
    paddingLeft: "10px",
    borderRadius: "3px",
    paddingRight: "10px",
  },
  sidebarWrapper: {
    position: "relative",
    height: "calc(100vh - 75px)",
    overflow: "auto",
    width: "260px",
    zIndex: "4",
    overflowScrolling: "touch",
    transitionProperty: "top, bottom, width",
    transitionDuration: ".2s, .2s, .35s",
    transitionTimingFunction: "linear, linear, ease",
    color: "inherit",
    paddingBottom: "30px",
  },
  listItems: {
    width: "auto",
    margin: "2px 10px 0",
    padding: "2px 15px",
    position: "relative",
    fontWeight: 300,
    paddingLeft: "10px",
    borderRadius: "3px",
    paddingRight: "10px",
    transition: "all 300ms linear",
  },
  expansionIcon: {
    transitionDuration: ".2s, .2s, .35s",
    transitionTimingFunction: "linear, linear, ease",
    transitionProperty: "all",
    marginRight:"0px",
    marginLeft:"-8px",
  },
  expansionIconNotExpanded: {
    transform: "rotate(-90deg)",
  },
  expnsionIconExpanded: {
    transform: "rotate(0deg)",
  },
  folderIcon:{
    marginRight:"5px",
    fontSize:"18px",
    color:"inherit",
    transition: "all 300ms linear",
  },
  iconBarWrapper:{
   zIndex:"4",
   display:"flex",
   justifyContent:"flex-end",
   marginTop:"5px",
  },
  childList:{
    marginLeft:"10px",
  }
});
